env:
  node: true
  es6: true
extends: "eslint:recommended"
parserOptions:
  ecmaFeatures:
    jsx: false
rules:
  accessor-pairs: error
  array-bracket-newline:
    - error
    - consistent
  array-bracket-spacing: error
  array-callback-return: error
  array-element-newline:
    - error
    - consistent
  arrow-body-style:
    - error
    - always
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
    - after: true
      before: true
  block-scoped-var: error
  block-spacing: error
  brace-style: error
  callback-return: error
  camelcase:
    - error
    - properties: never
  capitalized-comments:
    - error
    - never
  class-methods-use-this: error
  comma-dangle: error
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  complexity:
    - error
    - max: 5
  computed-property-spacing:
    - error
    - never
  consistent-return:
    - warn
  consistent-this:
    - error
    - self
  curly: error
  default-case: error
  default-case-last: error
  default-param-last: error
  dot-location:
    - error
    - property
  dot-notation: error
  eol-last: error
  eqeqeq:
    - error
    - always
    - null: ignore
  func-call-spacing: error
  func-name-matching: error
  func-names: error
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  function-paren-newline: error
  generator-star-spacing: error
  global-require: error
  grouped-accessor-pairs: error
  guard-for-in: error
  handle-callback-err: error
  id-blacklist: error
  id-denylist: error
  id-length: error
  id-match: error
  implicit-arrow-linebreak:
    - error
    - beside
  indent:
    - error
    - 2
  indent-legacy: "off"
  init-declarations: "off"
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  line-comment-position: error
  linebreak-style:
    - error
    - unix
  lines-around-comment: error
  lines-around-directive: error
  lines-between-class-members: error
  max-classes-per-file: error
  max-depth: error
  max-len: "off"
  max-lines: "off"
  max-lines-per-function: "off"
  max-nested-callbacks:
    - error
    - max: 5
  max-params: error
  max-statements: error
  max-statements-per-line: error
  multiline-comment-style: error
  multiline-ternary: error
  new-parens: error
  newline-after-var:
    - error
    - always
  newline-before-return: error
  newline-per-chained-call: error
  no-alert: error
  no-array-constructor: error
  no-await-in-loop: error
  no-bitwise: error
  no-buffer-constructor: error
  no-caller: error
  no-catch-shadow: error
  no-cond-assign:
    - error
    - always
  no-confusing-arrow: error
  no-console: error
  no-constructor-return: error
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-inline-comments: error
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-loss-of-precision: error
  no-magic-numbers: "off"
  no-mixed-operators: error
  no-mixed-requires: error
  no-multi-assign: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines: error
  no-native-reassign: error
  no-negated-condition: error
  no-negated-in-lhs: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-path-concat: error
  no-plusplus: error
  no-process-env: error
  no-process-exit: error
  no-promise-executor-return: error
  no-proto: error
  no-restricted-exports: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-spaced-func: error
  no-sync: error
  no-tabs: error
  no-template-curly-in-string: error
  no-ternary: "off"
  no-throw-literal: error
  no-trailing-spaces: "off"
  no-undef-init: error
  no-undefined: error
  no-underscore-dangle: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unreachable-loop: error
  no-unused-expressions: error
  no-use-before-define: error
  no-useless-backreference: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  no-void: error
  no-warning-comments: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  object-curly-newline: error
  object-curly-spacing:
    - error
    - never
  object-property-newline: error
  object-shorthand: error
  one-var:
    - error
    - never
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks: error
  padding-line-between-statements: error
  prefer-arrow-callback: "off"
  prefer-const: error
  prefer-destructuring: error
  prefer-exponentiation-operator: error
  prefer-named-capture-group: error
  prefer-numeric-literals: error
  prefer-object-spread: error
  prefer-promise-reject-errors: error
  prefer-reflect: "off"
  prefer-regex-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  quote-props: "off"
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  radix: error
  require-atomic-updates: error
  require-await: error
  require-jsdoc: error
  require-unicode-regexp: error
  rest-spread-spacing: error
  semi: error
  semi-spacing: error
  semi-style:
    - error
    - last
  sort-imports: error
  sort-keys: "off"
  sort-vars: error
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
    - error
    - never
  strict:
    - error
    - safe
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing: error
  template-tag-spacing: error
  unicode-bom:
    - error
    - never
  valid-jsdoc: error
  vars-on-top: error
  wrap-iife: error
  wrap-regex: error
  yield-star-spacing: error
  yoda: error
